# ═══ NEXUS Cortex — Central Nervous System ════════════════════
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-cortex
  namespace: nexus-prime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexus-cortex
  template:
    metadata:
      labels:
        app: nexus-cortex
    spec:
      containers:
      - name: cortex
        image: docker.io/library/nexus_prime_unified-nexus_cortex:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: nexus-config
        - secretRef:
            name: nexus-secrets
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@nexus-db:5432/$(POSTGRES_DB)"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-cortex
  namespace: nexus-prime
spec:
  selector:
    app: nexus-cortex
  ports:
  - port: 8090
    targetPort: 8090
