#!/bin/bash

# ============================================================================
# MRF_AUDIT CLEANUP SCRIPT
# ============================================================================
# Purpose: تنظيف وإعادة هيكلة مستودعات MRF_AUDIT
# Date: January 13, 2026
# Author: Generated by GitHub Copilot
# ============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Base directory
AUDIT_DIR="/workspaces/mrf103ARC-Namer/MRF_AUDIT"
BACKUP_DIR="/workspaces/mrf103ARC-Namer/MRF_AUDIT_BACKUP_$(date +%Y%m%d_%H%M%S)"

echo -e "${BLUE}============================================================================${NC}"
echo -e "${BLUE}   MRF_AUDIT CLEANUP & REORGANIZATION${NC}"
echo -e "${BLUE}============================================================================${NC}"
echo ""

# ============================================================================
# PHASE 0: BACKUP
# ============================================================================
phase0_backup() {
    echo -e "${YELLOW}[PHASE 0] Creating Full Backup...${NC}"
    
    if [ ! -d "$AUDIT_DIR" ]; then
        echo -e "${RED}Error: AUDIT_DIR not found at $AUDIT_DIR${NC}"
        exit 1
    fi
    
    mkdir -p "$BACKUP_DIR"
    
    echo "Copying to: $BACKUP_DIR"
    cp -r "$AUDIT_DIR/"* "$BACKUP_DIR/"
    
    echo -e "${GREEN}✓ Backup completed successfully${NC}"
    echo -e "Backup location: $BACKUP_DIR"
    echo ""
}

# ============================================================================
# PHASE 1: DELETE EMPTY REPOS
# ============================================================================
phase1_delete_empty() {
    echo -e "${YELLOW}[PHASE 1] Deleting Empty Repositories...${NC}"
    
    cd "$AUDIT_DIR" || exit
    
    EMPTY_REPOS=(
        "arc-firmware"
        "arc-interface"
        "arc-shared"
        "mrf103AR_VISION"
    )
    
    for repo in "${EMPTY_REPOS[@]}"; do
        if [ -d "$repo" ]; then
            echo "  Deleting: $repo"
            rm -rf "$repo"
            echo -e "  ${GREEN}✓ Deleted${NC}"
        else
            echo -e "  ${YELLOW}⚠ Not found: $repo${NC}"
        fi
    done
    
    echo -e "${GREEN}✓ Phase 1 completed${NC}"
    echo ""
}

# ============================================================================
# PHASE 2: DELETE DUPLICATE REPOS
# ============================================================================
phase2_delete_duplicates() {
    echo -e "${YELLOW}[PHASE 2] Deleting Duplicate Repositories...${NC}"
    
    cd "$AUDIT_DIR" || exit
    
    DUPLICATE_REPOS=(
        "arc-namer-cli"
        "arc-namer-vscode"
        "xbook-engine"
    )
    
    echo -e "${BLUE}Note: Keeping 'mrf103-arc-ecosystem' as the primary copy${NC}"
    
    for repo in "${DUPLICATE_REPOS[@]}"; do
        if [ -d "$repo" ]; then
            echo "  Deleting: $repo"
            rm -rf "$repo"
            echo -e "  ${GREEN}✓ Deleted${NC}"
        else
            echo -e "  ${YELLOW}⚠ Not found: $repo${NC}"
        fi
    done
    
    echo -e "${GREEN}✓ Phase 2 completed${NC}"
    echo ""
}

# ============================================================================
# PHASE 3: ARCHIVE FULL_AUDIT
# ============================================================================
phase3_archive() {
    echo -e "${YELLOW}[PHASE 3] Archiving FULL_AUDIT...${NC}"
    
    cd "$AUDIT_DIR" || exit
    
    if [ -d "FULL_AUDIT" ]; then
        ARCHIVE_DIR="$(dirname "$AUDIT_DIR")/ARCHIVE_BACKUP_$(date +%Y%m%d)"
        mkdir -p "$ARCHIVE_DIR"
        
        echo "  Moving FULL_AUDIT to: $ARCHIVE_DIR"
        mv FULL_AUDIT "$ARCHIVE_DIR/"
        
        echo -e "  ${GREEN}✓ Archived${NC}"
        echo -e "  Archive location: $ARCHIVE_DIR"
    else
        echo -e "  ${YELLOW}⚠ FULL_AUDIT not found${NC}"
    fi
    
    echo -e "${GREEN}✓ Phase 3 completed${NC}"
    echo ""
}

# ============================================================================
# PHASE 4: MERGE DOCUMENTATION
# ============================================================================
phase4_merge_docs() {
    echo -e "${YELLOW}[PHASE 4] Merging Documentation Repositories...${NC}"
    
    cd "$AUDIT_DIR" || exit
    
    if [ -d "arc-docs" ]; then
        echo "  Merging arc-ops → arc-docs"
        if [ -d "arc-ops/docs" ]; then
            mkdir -p arc-docs/docs/ops
            cp -r arc-ops/docs/* arc-docs/docs/ops/
            echo -e "  ${GREEN}✓ arc-ops merged${NC}"
            rm -rf arc-ops
        fi
        
        echo "  Merging arc-meta → arc-docs"
        if [ -d "arc-meta/docs" ]; then
            mkdir -p arc-docs/docs/meta
            cp -r arc-meta/docs/* arc-docs/docs/meta/
            echo -e "  ${GREEN}✓ arc-meta merged${NC}"
            rm -rf arc-meta
        fi
    else
        echo -e "  ${YELLOW}⚠ arc-docs not found${NC}"
    fi
    
    echo -e "${GREEN}✓ Phase 4 completed${NC}"
    echo ""
}

# ============================================================================
# PHASE 5: STATUS REPORT
# ============================================================================
phase5_report() {
    echo -e "${YELLOW}[PHASE 5] Generating Status Report...${NC}"
    
    cd "$AUDIT_DIR" || exit
    
    echo ""
    echo -e "${BLUE}Remaining Repositories:${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    
    local count=0
    for dir in */; do
        if [ -d "$dir" ]; then
            count=$((count + 1))
            size=$(du -sh "$dir" 2>/dev/null | cut -f1)
            echo -e "  ${GREEN}$count.${NC} ${dir%/} (${size})"
        fi
    done
    
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "Total Repositories: ${GREEN}$count${NC}"
    
    total_size=$(du -sh . 2>/dev/null | cut -f1)
    echo -e "Total Size: ${GREEN}$total_size${NC}"
    echo ""
    
    echo -e "${GREEN}✓ Phase 5 completed${NC}"
    echo ""
}

# ============================================================================
# PHASE 6: GIT OPERATIONS (OPTIONAL)
# ============================================================================
phase6_git_cleanup() {
    echo -e "${YELLOW}[PHASE 6] Git Cleanup (Optional)...${NC}"
    echo -e "${BLUE}This phase will run 'git gc' on remaining repositories${NC}"
    
    read -p "Do you want to run git cleanup? (y/N): " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cd "$AUDIT_DIR" || exit
        
        for dir in */; do
            if [ -d "$dir/.git" ]; then
                echo "  Cleaning: ${dir%/}"
                cd "$dir" || continue
                git gc --aggressive --prune=now 2>/dev/null || echo "    ⚠ Failed"
                cd ..
            fi
        done
        
        echo -e "${GREEN}✓ Git cleanup completed${NC}"
    else
        echo -e "${YELLOW}⚠ Skipped${NC}"
    fi
    
    echo ""
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================
main() {
    echo -e "${BLUE}Starting cleanup process...${NC}"
    echo ""
    
    # Confirm execution
    echo -e "${YELLOW}WARNING: This script will:${NC}"
    echo "  - Delete 4 empty repositories"
    echo "  - Delete 3 duplicate repositories"
    echo "  - Archive FULL_AUDIT folder"
    echo "  - Merge documentation repositories"
    echo ""
    echo -e "${BLUE}A backup will be created at:${NC}"
    echo "  $BACKUP_DIR"
    echo ""
    
    read -p "Do you want to continue? (y/N): " -n 1 -r
    echo
    
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}Operation cancelled by user${NC}"
        exit 0
    fi
    
    echo ""
    
    # Execute phases
    phase0_backup
    phase1_delete_empty
    phase2_delete_duplicates
    phase3_archive
    phase4_merge_docs
    phase5_report
    phase6_git_cleanup
    
    # Final message
    echo -e "${BLUE}============================================================================${NC}"
    echo -e "${GREEN}   CLEANUP COMPLETED SUCCESSFULLY!${NC}"
    echo -e "${BLUE}============================================================================${NC}"
    echo ""
    echo -e "${GREEN}Summary:${NC}"
    echo "  ✓ Backup created at: $BACKUP_DIR"
    echo "  ✓ Empty repositories deleted (4)"
    echo "  ✓ Duplicate repositories deleted (3)"
    echo "  ✓ FULL_AUDIT archived"
    echo "  ✓ Documentation merged"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Review remaining repositories"
    echo "  2. Update documentation"
    echo "  3. Setup CI/CD for core repositories"
    echo "  4. Push changes to GitHub"
    echo ""
    echo -e "${BLUE}Check the full report at:${NC}"
    echo "  $AUDIT_DIR/COMPREHENSIVE_AUDIT_REPORT.md"
    echo "  $AUDIT_DIR/QUICK_SUMMARY_TABLE.md"
    echo ""
}

# ============================================================================
# DRY RUN MODE (for testing)
# ============================================================================
dry_run() {
    echo -e "${YELLOW}[DRY RUN MODE - No changes will be made]${NC}"
    echo ""
    
    cd "$AUDIT_DIR" || exit
    
    echo -e "${BLUE}Would delete empty repositories:${NC}"
    for repo in arc-firmware arc-interface arc-shared mrf103AR_VISION; do
        if [ -d "$repo" ]; then
            echo "  - $repo"
        fi
    done
    echo ""
    
    echo -e "${BLUE}Would delete duplicate repositories:${NC}"
    for repo in arc-namer-cli arc-namer-vscode xbook-engine; do
        if [ -d "$repo" ]; then
            echo "  - $repo"
        fi
    done
    echo ""
    
    echo -e "${BLUE}Would archive:${NC}"
    if [ -d "FULL_AUDIT" ]; then
        echo "  - FULL_AUDIT"
    fi
    echo ""
    
    echo -e "${BLUE}Would merge documentation:${NC}"
    echo "  - arc-ops → arc-docs"
    echo "  - arc-meta → arc-docs"
    echo ""
}

# ============================================================================
# SCRIPT ENTRY POINT
# ============================================================================

# Check if dry-run flag is provided
if [ "$1" == "--dry-run" ] || [ "$1" == "-d" ]; then
    dry_run
else
    main
fi
