FROM python:3.10-slim

WORKDIR /app

# نسخ المتطلبات من داخل مجلد الكود
COPY edge-tts-repo/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# نسخ باقي الكود
COPY edge-tts-repo/ .

EXPOSE 8000
CMD ["python", "main.py"]
