#!/bin/bash

echo "🔧 Railway Deployment Troubleshooting Guide"
echo "=========================================="
echo ""

echo "📋 المشاكل الشائعة وحلولها:"
echo ""

echo "1️⃣  APPLICATION NOT FOUND (404)"
echo "   السبب المحتمل:"
echo "   - Build فشل"
echo "   - START command خطأ"
echo "   - PORT variable مش محدد صح"
echo ""
echo "   الحل:"
echo "   • روح Railway Dashboard → mrf103-arc-ecosystem"
echo "   • اضغط Deployments → شوف آخر deployment"
echo "   • اضغط View Logs"
echo "   • ابحث عن:"
echo "     - Build errors"
echo "     - TypeScript compilation errors"
echo "     - Missing dependencies"
echo "     - Port binding errors"
echo ""

echo "2️⃣  BUILD ERRORS"
echo "   الأخطاء المحتملة:"
echo "   - package-lock.json مفقود ✅ (تم الإصلاح)"
echo "   - Dependencies مش متوافقة"
echo "   - TypeScript errors"
echo ""
echo "   التحقق:"
echo "   • في Railway Logs ابحث عن:"
echo "     - 'npm ci' errors"
echo "     - 'tsc' compilation errors"
echo "     - 'Cannot find module' errors"
echo ""

echo "3️⃣  START COMMAND FAILURE"
echo "   المشكلة:"
echo "   - الأمر 'npm start' فشل"
echo "   - dist/ folder مش موجود"
echo "   - server/index.js مش موجود"
echo ""
echo "   الحل:"
echo "   • تأكد إن:"
echo "     - Build command: npm run build"
echo "     - Start command: npm start"
echo "     - package.json → scripts.start صحيح"
echo ""

echo "4️⃣  PORT CONFIGURATION"
echo "   المشكلة:"
echo "   - App بتستمع على port غلط"
echo "   - Railway PORT variable مش معرف"
echo ""
echo "   الحل:"
echo "   • في الكود:"
echo "     const PORT = process.env.PORT || 5000;"
echo "   • في Railway:"
echo "     PORT variable يجب أن يكون محدد (Railway يضيفه تلقائياً)"
echo ""

echo "5️⃣  ENVIRONMENT VARIABLES"
echo "   المتغيرات المطلوبة:"
echo "   ✅ NODE_ENV=production"
echo "   ✅ PORT (Railway يضيفه تلقائياً)"
echo "   ✅ DATABASE_URL"
echo "   ✅ OPENAI_API_KEY"
echo "   ✅ SUPABASE_URL"
echo "   ✅ SUPABASE_ANON_KEY"
echo "   ✅ SESSION_SECRET"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 خطوات التشخيص:"
echo ""
echo "1. افتح Railway Dashboard:"
echo "   https://railway.app/dashboard"
echo ""
echo "2. اختار مشروع: mrf103-arc-ecosystem"
echo ""
echo "3. اضغط Deployments (آخر deployment)"
echo ""
echo "4. اضغط View Logs"
echo ""
echo "5. ابحث عن الأخطاء:"
echo "   - Build stage: أخطاء npm install أو npm run build"
echo "   - Deploy stage: أخطاء npm start"
echo "   - Runtime: أخطاء التطبيق"
echo ""
echo "6. انسخ الأخطاء وأرسلها"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 فحص سريع للإعدادات:"
echo ""

echo "   railway.json:"
echo "   ✓ builder: DOCKERFILE"
echo "   ✓ startCommand: npm start"
echo "   ✓ healthcheckPath: /api/health"
echo ""

echo "   Dockerfile:"
echo "   ✓ Multi-stage build"
echo "   ✓ npm ci --legacy-peer-deps"
echo "   ✓ npm run build:client && npm run build:server"
echo "   ✓ CMD [\"npm\", \"start\"]"
echo ""

echo "   package.json:"
echo "   ✓ build: npm run build:client && npm run build:server"
echo "   ✓ build:client: vite build"
echo "   ✓ build:server: tsc --outDir dist"
echo "   ✓ start: node dist/server/index.js"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ الإجراء السريع:"
echo ""
echo "1. افتح Railway Logs"
echo "2. انسخ آخر 50 سطر من الأخطاء"
echo "3. أرسلهم هنا"
echo "4. سنحل المشكلة مباشرة!"
echo ""
