#!/bin/bash

# 🚨 Railway Deployment Fix - Quick Checklist

echo "=================================================="
echo "🔧 RAILWAY 502 ERROR - FIX CHECKLIST"
echo "=================================================="
echo ""

echo "✅ COMPLETED:"
echo "  1. Removed hardcoded ENV PORT=9002 from Dockerfile"
echo "  2. Committed and pushed changes to GitHub (commit: aaa9dd8)"
echo ""

echo "📋 NEXT STEPS (Manual on Railway Dashboard):"
echo ""
echo "1. Go to: https://railway.app"
echo "   └─ Select project: mrf103ARC-Namer"
echo ""
echo "2. Check 'Variables' tab:"
echo "   ├─ If PORT exists → DELETE IT"
echo "   ├─ Railway auto-injects PORT dynamically"
echo "   └─ Required vars:"
echo "      ├─ DATABASE_URL ✓"
echo "      ├─ SUPABASE_URL ✓"
echo "      ├─ SUPABASE_KEY ✓"
echo "      ├─ ARC_OPERATOR_PASSWORD ✓"
echo "      ├─ SESSION_SECRET ✓"
echo "      └─ NODE_ENV=production ✓"
echo ""
echo "3. Monitor Deployment:"
echo "   ├─ Railway should auto-deploy from GitHub push"
echo "   ├─ Watch logs for: '✅ Server is live and listening on port XXXX'"
echo "   └─ Wait 2-3 minutes"
echo ""
echo "4. Test the Fix:"
echo "   $ curl -I https://app.mrf103.com"
echo "   Expected: HTTP/2 200"
echo ""
echo "   $ curl https://app.mrf103.com/api/health"
echo "   Expected: {\"status\":\"healthy\",...}"
echo ""

echo "=================================================="
echo "🔍 TROUBLESHOOTING:"
echo "=================================================="
echo ""
echo "If still 502:"
echo "  1. Check Railway logs for errors:"
echo "     - EADDRINUSE (port conflict)"
echo "     - Database connection errors"
echo "     - Missing environment variables"
echo ""
echo "  2. Verify build succeeded:"
echo "     - Build command: npm run build"
echo "     - Check dist/ folder was created"
echo "     - Start command: npm start"
echo ""
echo "  3. Manual redeploy:"
echo "     Railway Dashboard → Deploy → Trigger Deploy"
echo ""

echo "=================================================="
echo "📊 Expected Railway Logs:"
echo "=================================================="
echo ""
echo "[Railway] Building from commit aaa9dd8..."
echo "[Railway] Running: npm run build"
echo "[Railway] Build complete"
echo "[Railway] Starting: npm start"
echo "[App] ✅ Server is live and listening on 0.0.0.0:XXXX"
echo "[App] 🌍 Environment: production"
echo "[App] Database connected"
echo "[App] Supabase initialized"
echo ""

echo "=================================================="
echo "Last updated: $(date)"
echo "=================================================="
