# ═══ LiteLLM Sovereignty Proxy ═════════════════════════════════
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: nexus-prime
data:
  config.yaml: |
    model_list:
      - model_name: gemini-1.5-flash
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
      - model_name: gemini-2.5-flash
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
      - model_name: gemini-pro
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
      - model_name: gpt-4o
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
      - model_name: gpt-4o-mini
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
      - model_name: gpt-4
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
      - model_name: claude-3-5-sonnet-20241022
        litellm_params:
          model: ollama/llama3.2:3b
          api_base: http://nexus-ollama:11434
    general_settings:
      master_key: sk-nexus-sovereign-mrf103
      drop_params: true
    litellm_settings:
      drop_params: true
      set_verbose: false
      num_retries: 2
      request_timeout: 120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-litellm
  namespace: nexus-prime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-litellm
  template:
    metadata:
      labels:
        app: nexus-litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        args: ["--config", "/app/config.yaml", "--port", "4000"]
        ports:
        - containerPort: 4000
        env:
        - name: LITELLM_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: nexus-secrets
              key: LITELLM_MASTER_KEY
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/liveliness
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: litellm-config
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-litellm
  namespace: nexus-prime
spec:
  selector:
    app: nexus-litellm
  ports:
  - port: 4000
    targetPort: 4000
