# ═══════════════════════════════════════════════════════════════════════════
# NEXUS PRIME — Meta-Orchestrator K8s Manifests (Production-Grade)
# ═══════════════════════════════════════════════════════════════════════════
# Features:
#   ✅ Headless Service for gRPC Client-Side Load Balancing
#   ✅ Horizontal Pod Autoscaler (HPA) - 3 to 10 replicas at 70% CPU
#   ✅ Pod Disruption Budget (PDB) - minimum 2 pods always available
#   ✅ Health Probes - liveness and readiness with grpc_health_probe
#   ✅ RBAC - ServiceAccount + Role + RoleBinding
#   ✅ Resource Requests/Limits
#   ✅ Prometheus Metrics Annotations
#   ✅ Rolling Update Strategy - zero downtime deployments
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: v1
kind: Namespace
metadata:
  name: nexus-prime
  labels:
    name: nexus-prime
    environment: production

---
# ═══════════════════════════════════════════════════════════════════════════
# SERVICE ACCOUNT (RBAC)
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-orchestrator
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator

---
# ═══════════════════════════════════════════════════════════════════════════
# ROLE (RBAC) - Pod read permissions for service discovery
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus-orchestrator-role
  namespace: nexus-prime
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
# ═══════════════════════════════════════════════════════════════════════════
# ROLE BINDING (RBAC)
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-orchestrator-binding
  namespace: nexus-prime
subjects:
  - kind: ServiceAccount
    name: nexus-orchestrator
    namespace: nexus-prime
roleRef:
  kind: Role
  name: nexus-orchestrator-role
  apiGroup: rbac.authorization.k8s.io

---
# ═══════════════════════════════════════════════════════════════════════════
# HEADLESS SERVICE (for gRPC Client-Side Load Balancing)
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: v1
kind: Service
metadata:
  name: nexus-orchestrator
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  clusterIP: None  # Headless service for gRPC
  selector:
    app: nexus-orchestrator
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  publishNotReadyAddresses: false

---
# ═══════════════════════════════════════════════════════════════════════════
# DEPLOYMENT (with Health Probes, Resource Limits, Rolling Update)
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-orchestrator
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator
    version: v1.1.0
spec:
  replicas: 3  # Start with 3 for HA, HPA will scale 3-10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         # Allow 1 extra pod during rollout
      maxUnavailable: 0   # Zero downtime - always keep all pods running
  selector:
    matchLabels:
      app: nexus-orchestrator
  template:
    metadata:
      labels:
        app: nexus-orchestrator
        version: v1.1.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: nexus-orchestrator
      
      # Anti-affinity - spread pods across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nexus-orchestrator
                topologyKey: kubernetes.io/hostname
      
      containers:
        - name: orchestrator
          image: localhost:5000/nexus_orchestrator:v1.1.0
          imagePullPolicy: Always
          
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          
          env:
            - name: CORTEX_URL
              value: "http://nexus-cortex:8090"
            - name: REDIS_URL
              value: "redis://nexus-redis:6379/0"
            - name: GRPC_PORT
              value: "50051"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          
          # ── Resource Limits (Production-Grade) ──
          resources:
            requests:
              memory: "256Mi"  # Increased from 128Mi
              cpu: "250m"      # 0.25 CPU cores
            limits:
              memory: "512Mi"
              cpu: "1000m"     # 1 CPU core max
          
          # ── Health Probes (using grpc_health_probe) ──
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:50051
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:50051
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          
          # ── Graceful Shutdown ──
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 5  # Allow in-flight requests to complete

---
# ═══════════════════════════════════════════════════════════════════════════
# HORIZONTAL POD AUTOSCALER (HPA) - Scale from 3 to 10 replicas
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexus-orchestrator-hpa
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexus-orchestrator
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale up when CPU > 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Scale up when memory > 80%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5min before scaling down
      policies:
        - type: Percent
          value: 50  # Scale down max 50% of pods at a time
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
        - type: Percent
          value: 100  # Double pods if needed
          periodSeconds: 15
        - type: Pods
          value: 2  # Or add 2 pods
          periodSeconds: 15
      selectPolicy: Max  # Take the faster option

---
# ═══════════════════════════════════════════════════════════════════════════
# POD DISRUPTION BUDGET (PDB) - Ensure minimum 2 pods always available
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nexus-orchestrator-pdb
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator
spec:
  minAvailable: 2  # Always keep at least 2 pods running
  selector:
    matchLabels:
      app: nexus-orchestrator

---
# ═══════════════════════════════════════════════════════════════════════════
# CONFIGMAP (Optional - for dynamic configuration)
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-orchestrator-config
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator
data:
  STALENESS_THRESHOLD_SEC: "60"
  STALENESS_CHECK_INTERVAL: "30"
  HEARTBEAT_INTERVAL: "10"
  MAX_RETRIES: "10"
  INITIAL_BACKOFF: "1.0"
  MAX_BACKOFF: "60.0"

---
# ═══════════════════════════════════════════════════════════════════════════
# NETWORK POLICY (Optional - for security)
# ═══════════════════════════════════════════════════════════════════════════

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexus-orchestrator-netpol
  namespace: nexus-prime
  labels:
    app: nexus-orchestrator
spec:
  podSelector:
    matchLabels:
      app: nexus-orchestrator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nexus-prime
      ports:
        - protocol: TCP
          port: 50051  # gRPC
        - protocol: TCP
          port: 9090   # Metrics
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: nexus-prime
      ports:
        - protocol: TCP
          port: 8090   # Cortex
        - protocol: TCP
          port: 6379   # Redis
    - to:  # Allow DNS
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
