code --install-extension الامتدادات المثبتة في الموقع Codespaces: laughing space guacamole:
code --install-extension buildwithlayer.railway-integration-expert-x3o0c
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension davidanson.vscode-markdownlint
code --install-extension digu3120.flutter-apk-finder
code --install-extension dotjoshjohnson.xml
code --install-extension espressif.esp-idf-extension
code --install-extension gautamsagarmallela.fastapienvironment
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension google.gemini-cli-vscode-ide-companion
code --install-extension itscap.apk-locator
code --install-extension lekman.tts-code
code --install-extension loyieking.smalise
code --install-extension manassahu.openai-developer
code --install-extension mechatroner.rainbow-csv
code --install-extension miroreo.replit
code --install-extension mrverdant13.esp32-pm
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-serial-monitor
code --install-extension openai.chatgpt
code --install-extension platformio.platformio-ide
code --install-extension ronaldosena.arduino-snippets
code --install-extension surendrajat.apklab
code --install-extension twilio.vscode-twilio
code --install-extension vscjava.vscode-gradle
