#!/bin/bash

echo "🚂 Railway Deployment Guide"
echo "=========================="
echo ""
echo "📋 Environment Variables المطلوبة:"
echo ""
echo "DATABASE_URL=postgresql://user:pass@host:5432/dbname"
echo "JWT_SECRET=your-super-secret-jwt-key-change-this"
echo "JWT_EXPIRES_IN=7d"
echo "NODE_ENV=production"
echo "PORT=\${{PORT}}"
echo ""
echo "Optional (if needed):"
echo "SUPABASE_URL=https://your-project.supabase.co"
echo "SUPABASE_ANON_KEY=your-key"
echo "OPENAI_API_KEY=sk-proj-NEW-KEY-HERE"
echo "REDIS_URL=redis://..."
echo ""
echo "=========================="
echo "🔗 Railway Dashboard:"
echo "https://railway.app/new"
echo ""
echo "📝 Steps:"
echo "1. Click 'New Project'"
echo "2. Select 'Deploy from GitHub repo'"
echo "3. Choose: firas103103-oss/mrf103ARC-Namer"
echo "4. Railway will detect Dockerfile automatically"
echo "5. Add the environment variables above"
echo "6. Click Deploy!"
echo ""
echo "✅ Done! App will be at: https://your-app.up.railway.app"
